pyvec/cz.pycon.org-2019

tests/modifications.sql, tests/test_data.sql
Testovací data pro budoucí testy. Neměly by obsahovat žádná neveřejná data. Kontroloval jsem to několikrát, ale stejně prosím o review pro jistotu.
@mcurlej @coudy99
=> Add test data extracted from PyconCZ 2018 database

README.md, pyconcz/settings/local_template.py, pyconcz/settings/local_template_dev.py
=> database name now the same in local_template.py

pyconcz/templates/default/pages/privacy.html, pyconcz/templates/default/proposals/talks_about.html
Fixes: https://github.com/pyvec/cz.pycon.org-2019/issues/48
=> Sync design of main headings

README.md
Documenting rules for merging, deploying etc
=> description of git workflow

pyconcz/templates/default/pages/_ticket-button.html, pyconcz/templates/default/pages/_ticket-pricing.html, pyconcz/templates/default/pages/tickets.html
=> Secret tickets

pyconcz/templates/default/pages/_ticket-button.html
=> fix: works for a case when secret ticket has more than 3 left

pyconcz/templates/__nav-link.html
=> fix: nav-link back, really

pyconcz/templates/pages/sponsors_offer.html
@benabraham Promin za prodlevu!
=> sponsors_offer: Small adjustments

pyconcz/templates/__nav-link.html, pyconcz/urls.py
+ better error message for link template
=> talks links working

pyconcz/templates/programme/__preview-session.html
=> requirements and attendee limits shown in preview

pyconcz/templates/programme/preview.html
=> export table added

pyconcz/templates/pages/homepage.html
+ link to board game night ready
=> links to talks and workshops on homepage

pyconcz/templates/programme/_base_detail.html, pyconcz/templates/programme/_base_list.html
=> Sessions fixes

pyconcz/templates/programme/_base_detail.html
=> workshop hours public

pyconcz/templates/_menu_base.html, pyconcz/templates/proposals/financial_aid_about.html, pyconcz/templates/tickets/__content.html
=> Ticket finaid

pyconcz/templates/pages/venue.html
=> Fix link "getting to the venue"

pyconcz/templates/pages/venue.html
I think that "On Friday and Thursday everything will be happening at" should be "On Friday and Saturday"
=> Correct day update

pyconcz/programme/admin.py, pyconcz/programme/models.py, pyconcz/programme/views.py, pyconcz/templates/programme/slot_schedule.html
This is needed to be able to add arbitrary items to the schedule i. e.
add breakfast, afterparty info etc.
Issue ID: #20
Signed-off-by: Martin Curlej <mcurlej@redhat.com>
=> Added utility item to the pycon schedule

pyconcz/programme/management/commands/talks_to_slots.py, pyconcz/programme/management/commands/ws_to_slots.py
=> Fix manage commands for copying talks/ws to slots

pyconcz/templates/intermission/index.html
This should hopefully work with most presentation clickers.
Spacebar resumes the cycle.
=> Allow Intermission to be controlled as slides

2020/cfp.html
There was a grammar error:
Its is a possessive form of the pronoun it, meaning belonging to it.
It's is a contraction of the words it is or it has.
Either way, this sounds better to me.
=> Reword the CFP notification pitch

2020/coc.html
Signed-off-by: Veronika Kabatova <veronicca114@gmail.com>
=> Update CoC contact info

pyconcz/programme/models.py, pyconcz/programme/views.py, pyconcz/templates/programme/__other_sessions.html, pyconcz/templates/programme/_base_detail.html, pyconcz/templates/programme/talk_detail.html, pyconcz/templates/programme/workshop_detail.html
=> Parallel sessions

2023/cfp-guide.html, 2023/cfp-pruvodce.html, 2023/cfp.html
Updated based on feedback in the docs.
=> WIP: CfP guide

2023/privacy-policy.html
=> Updates to privacy policy
